const { app, BrowserWindow, globalShortcut, clipboard, ipcMain, Menu, net, desktopCapturer, screen } = require('electron');
const { execSync, spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

// Anthropic model used for all Claude API calls.
// The previous Sonnet 4 model (dated 20250514) was retired from the API on 2026-06-15;
// claude-sonnet-4-6 (Claude Sonnet 4.6) is its API-compatible same-tier successor.
const CLAUDE_MODEL = 'claude-sonnet-4-6';

// Build provenance for Settings > About. Generated by scripts/gen-build-info.js
// at build time; falls back to package version with a 'dev' commit when absent
// (e.g. running unpackaged via `npm start`). BOM-stripped defensively.
let BUILD_INFO;
try {
    BUILD_INFO = JSON.parse(
        fs.readFileSync(path.join(__dirname, 'build-info.json'), 'utf8').replace(/^\uFEFF/, '')
    );
} catch {
    BUILD_INFO = { version: require('./package.json').version, commit: 'dev', builtAt: null, runNumber: null };
}

let ahkProcess = null;

function getAhkPaths() {
    const exeDir = path.dirname(process.execPath);
    const resourcesPath = path.join(exeDir, 'resources', 'autohotkey');
    const devPath = path.join(__dirname, 'autohotkey');
    const ahkBinDir = fs.existsSync(resourcesPath) ? resourcesPath : devPath;

    const runtimeDir = process.env.PORTABLE_EXECUTABLE_DIR
        || path.dirname(process.execPath)
        || devPath;

    return {
        exe:    path.join(ahkBinDir, 'AutoHotkey64.exe'),
        script: path.join(ahkBinDir, 'heidi-hotkeys.ahk'),
        config: path.join(runtimeDir, 'heidi-config.ini'),
        slots:  path.join(runtimeDir, 'heidi-slots.json'),
        dir:    runtimeDir
    };
}

function launchAHK() {
    if (process.platform !== 'win32') return;
    const { exe, script } = getAhkPaths();
    if (!fs.existsSync(exe)) { console.error('AutoHotkey64.exe not found at:', exe); return; }
    if (!fs.existsSync(script)) { console.error('heidi-hotkeys.ahk not found at:', script); return; }
    try {
        ahkProcess = spawn(exe, [script], { detached: false, stdio: 'ignore', windowsHide: true });
        ahkProcess.on('error', (e) => console.error('AHK launch error:', e.message));
        ahkProcess.on('exit', (code) => { console.log('AHK exited with code:', code); ahkProcess = null; });
        console.log('AutoHotkey launched, PID:', ahkProcess.pid);
    } catch (e) { console.error('Failed to launch AHK:', e.message); }
}

function killAHK() {
    if (ahkProcess) { try { ahkProcess.kill(); } catch(e) {} ahkProcess = null; }
    if (slotsWatcher) { try { slotsWatcher.close(); } catch(e) {} slotsWatcher = null; }
}

function writeAhkConfig(examDotPhrase) {
    if (process.platform !== 'win32') return;
    const { config } = getAhkPaths();
    const encoded = (examDotPhrase || '').replace(/\n/g, '\\n').replace(/\r/g, '');
    const ini = `[Heidi]\nExamDotPhrase=${encoded}\n`;
    try { fs.writeFileSync(config, ini, 'utf-8'); } catch (e) { console.error('Failed to write AHK config:', e.message); }
}

let slotsWatcher = null;

function sendSlotState() {
    if (!mainWindow) return;
    const exam = getExamSlot();
    mainWindow.webContents.send('capture-result', {
        success: true,
        hpiLoaded: !!slots.hpi,
        apLoaded: !!slots.ap,
        examLoaded: !!exam,
        hpiPreview: slots.hpi ? slots.hpi.substring(0, 80) : null,
        apPreview: slots.ap ? slots.ap.substring(0, 80) : null,
        examPreview: exam ? exam.substring(0, 80) : null,
        bulletsLoading: false
    });
}

function watchSlotsFile() {
    if (process.platform !== 'win32') return;
    const { dir } = getAhkPaths();
    readSlotsFile();
    try {
        slotsWatcher = fs.watch(dir, (eventType, filename) => {
            if (filename === 'heidi-slots.json') { setTimeout(() => readSlotsFile(), 150); }
        });
    } catch (e) { console.error('Failed to watch slots dir:', e.message); }
}

function readSlotsFile() {
    const { slots: slotsPath } = getAhkPaths();
    try {
        if (!fs.existsSync(slotsPath)) return;
        const raw = fs.readFileSync(slotsPath, 'utf-8').replace(/^\uFEFF/, '');
        const data = JSON.parse(raw);
        if (data.hpi !== undefined) slots.hpi = data.hpi || null;
        if (data.ap  !== undefined) slots.ap  = data.ap  || null;
        sendSlotState();
    } catch (e) { console.error('Failed to read slots file:', e.message); }
}

// Portable config
const DEFAULTS = {
    hpiHotkey: 'PageUp',
    apHotkey: 'PageDown',
    heidiCopyEnabled: true,
    captureHotkey: 'F8',
    pasteHotkey1: 'F9',
    pasteHotkey2: 'F10',
    pasteHotkey3: 'F11',
    examDotPhrase: '',
    claudeApiKey: '',
    customClaudeInstructions: '',
    customAttestationTemplate: '',
    windowBounds: { width: 400, height: 500 }
};

function getConfigPath() {
    const portableDir = process.env.PORTABLE_EXECUTABLE_DIR;
    if (portableDir) {
        const portablePath = path.join(portableDir, 'MedicalNoteAttestor-config.json');
        if (fs.existsSync(portablePath)) {
            return portablePath;
        }
    }
    const configDir = path.join(process.env.APPDATA || path.join(require('os').homedir(), 'AppData', 'Roaming'), 'MedicalNoteAttestor');
    if (!fs.existsSync(configDir)) {
        fs.mkdirSync(configDir, { recursive: true });
    }
    return path.join(configDir, 'config.json');
}

function getSavePath() {
    const paths = [];
    const portableDir = process.env.PORTABLE_EXECUTABLE_DIR;
    if (portableDir) {
        paths.push(path.join(portableDir, 'MedicalNoteAttestor-config.json'));
    }
    const configDir = path.join(process.env.APPDATA || path.join(require('os').homedir(), 'AppData', 'Roaming'), 'MedicalNoteAttestor');
    if (!fs.existsSync(configDir)) {
        fs.mkdirSync(configDir, { recursive: true });
    }
    paths.push(path.join(configDir, 'config.json'));
    return paths;
}

function loadConfig() {
    try {
        const configPath = getConfigPath();
        if (fs.existsSync(configPath)) {
            const raw = fs.readFileSync(configPath, 'utf-8');
            return { ...DEFAULTS, ...JSON.parse(raw) };
        }
    } catch (e) {
        console.error('Failed to load config:', e);
    }
    return { ...DEFAULTS };
}

function saveConfig(data) {
    const json = JSON.stringify(data, null, 2);
    for (const p of getSavePath()) {
        try {
            fs.writeFileSync(p, json, 'utf-8');
        } catch (e) {
            console.error('Failed to save config to', p, e);
        }
    }
}

const configData = loadConfig();
const store = {
    get: (key) => configData[key] !== undefined ? configData[key] : DEFAULTS[key],
    set: (key, value) => { configData[key] = value; saveConfig(configData); }
};

// In-memory note slots — reset on quit (patient safety)
const slots = { hpi: null, ap: null };

function getExamSlot() {
    return store.get('examDotPhrase') || '';
}

let mainWindow;
let settingsWindow;
let overlayWindow;

// Heidi section headers
const HPI_HEADERS = [
    'Interval history, HPI:',
    'History of Present Illness (HPI):',
    'History of Present Illness:'
];
const AP_HEADERS = [
    'Assessment and plan:',
    'Assessment and Plan:',
    'Assessment & Plan:',
    'Assessment & plan:',
    'Assessment/Plan:',
    'A&P:',
    'A/P:',
    'ASSESSMENT AND PLAN:',
    'ASSESSMENT & PLAN:',
    'Assessment and Plan',
    'Assessment and plan',
    'Assessment & Plan'
];

function findAPStart(text) {
    for (const header of AP_HEADERS) {
        const idx = text.indexOf(header);
        if (idx !== -1) {
            return { index: idx, length: header.length };
        }
    }
    // Case-insensitive fallback
    const lower = text.toLowerCase();
    const patterns = ['assessment and plan', 'assessment & plan', 'assessment/plan'];
    for (const pat of patterns) {
        const idx = lower.indexOf(pat);
        if (idx !== -1) {
            // Find the end of this line header (look for colon or newline)
            let end = idx + pat.length;
            if (text[end] === ':') end++;
            return { index: idx, length: end - idx };
        }
    }
    return null;
}

function createMainWindow() {
    const bounds = store.get('windowBounds');

    mainWindow = new BrowserWindow({
        width: bounds.width,
        height: bounds.height,
        minWidth: 180,
        minHeight: 36,
        alwaysOnTop: true,
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
            preload: path.join(__dirname, 'preload.js')
        }
    });

    mainWindow.loadFile(path.join(__dirname, 'index.html'));
    mainWindow.setMenu(null);

    mainWindow.webContents.on('did-finish-load', () => { sendSlotState(); });

    mainWindow.on('resize', () => {
        const { width, height } = mainWindow.getBounds();
        store.set('windowBounds', { width, height });
    });

    mainWindow.on('closed', () => {
        mainWindow = null;
    });

    const menuTemplate = [
        {
            label: 'File',
            submenu: [{ role: 'quit' }]
        },
        {
            label: 'Edit',
            submenu: [
                { role: 'copy' },
                { role: 'paste' },
                { role: 'selectAll' }
            ]
        },
        {
            label: 'Settings',
            submenu: [{
                label: 'Preferences...',
                accelerator: 'CmdOrCtrl+,',
                click: () => openSettings()
            }]
        }
    ];

    const menu = Menu.buildFromTemplate(menuTemplate);
    Menu.setApplicationMenu(menu);
}

function openSettings() {
    if (settingsWindow) {
        settingsWindow.focus();
        return;
    }

    settingsWindow = new BrowserWindow({
        width: 550,
        height: 600,
        parent: mainWindow,
        modal: false,
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
            preload: path.join(__dirname, 'preload.js')
        }
    });

    settingsWindow.loadFile(path.join(__dirname, 'settings.html'));
    settingsWindow.setMenu(null);

    settingsWindow.on('closed', () => {
        settingsWindow = null;
        registerHotkeys();
    });
}

function registerHotkeys() {
    try {
        globalShortcut.unregisterAll();

        const captureKey = store.get('captureHotkey') || 'F8';
        const paste1Key  = store.get('pasteHotkey1')  || 'F9';
        const paste2Key  = store.get('pasteHotkey2')  || 'F10';
        const paste3Key  = store.get('pasteHotkey3')  || 'F11';
        const hpiKey     = store.get('hpiHotkey')     || 'PageUp';
        const apKey      = store.get('apHotkey')      || 'PageDown';

        const tryRegister = (key, fn) => {
            try {
                if (key) {
                    const ok = globalShortcut.register(key, fn);
                    console.log(`Hotkey "${key}": ${ok ? 'registered OK' : 'FAILED TO REGISTER'}`);
                }
            } catch (e) {
                console.error(`Hotkey "${key}" threw: ${e.message}`);
            }
        };

        if (process.platform !== 'win32') {
            tryRegister(captureKey, () => { performCapture().catch(e => console.error(e)); });
            tryRegister(paste1Key,  () => pasteSlot('hpi'));
            tryRegister(paste2Key,  () => pasteSlot('exam'));
            tryRegister(paste3Key,  () => pasteSlot('ap'));
        }
        // Legacy single-section hotkeys — keep on all platforms as fallback
        tryRegister(hpiKey, () => extractAndCopySection('hpi'));
        tryRegister(apKey,  () => extractAndCopySection('ap'));

    } catch (err) {
        console.error('registerHotkeys failed:', err.message);
    }
}

async function extractAndCopySection(section) {
    try {
        // Send Ctrl+A then Ctrl+C to the foreground window (e.g. Heidi)
        const psScript = "Add-Type -AssemblyName System.Windows.Forms; Start-Sleep -Milliseconds 50; [System.Windows.Forms.SendKeys]::SendWait('^a'); Start-Sleep -Milliseconds 100; [System.Windows.Forms.SendKeys]::SendWait('^c'); Start-Sleep -Milliseconds 100;";
        execSync(`powershell -NoProfile -Command "${psScript}"`, { timeout: 3000 });
    } catch (e) {
        console.error('Failed to auto-copy from foreground window:', e);
    }

    // Small delay to let clipboard populate
    await new Promise(r => setTimeout(r, 150));

    const text = clipboard.readText();
    if (!text) return;

    let extracted;
    if (section === 'hpi') {
        extracted = extractHPI(text);
    } else {
        extracted = extractAP(text);
    }

    if (extracted) {
        clipboard.writeText(extracted);
        if (mainWindow) {
            mainWindow.webContents.send('section-copied', section);
        }
    }
}

function extractHPI(text) {
    let hpiStart = -1;
    for (const header of HPI_HEADERS) {
        const idx = text.indexOf(header);
        if (idx !== -1) {
            hpiStart = idx + header.length;
            break;
        }
    }
    if (hpiStart === -1) {
        console.log('HPI header not found in text. First 200 chars:', text.substring(0, 200));
        return null;
    }
    const ap = findAPStart(text);
    if (!ap || ap.index <= hpiStart) {
        console.log('A&P header not found after HPI');
        return null;
    }
    return cleanUpText(text.substring(hpiStart, ap.index));
}

function extractAP(text) {
    const ap = findAPStart(text);
    if (!ap) {
        console.log('A&P header not found in text. First 500 chars:', text.substring(0, 500));
        return null;
    }
    console.log('Found A&P header at index', ap.index, ':', text.substring(ap.index, ap.index + 30));
    return cleanUpText(text.substring(ap.index + ap.length));
}

function cleanUpText(text) {
    let cleaned = text.replace(/\*\*/g, '').replace(/\*/g, '');
    cleaned = cleaned.trim();
    const lines = cleaned.split('\n');
    let startIdx = 0;
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim()) { startIdx = i; break; }
    }
    return lines.slice(startIdx).join('\n');
}

// ── v2 Slot capture and paste ──────────────────────────────────────────────

async function performCapture() {
    // Step 1: Auto-trigger Ctrl+A + Ctrl+C in the active foreground window (Heidi)
    try {
        const psScript = [
            'Add-Type -AssemblyName System.Windows.Forms;',
            'Start-Sleep -Milliseconds 50;',
            '[System.Windows.Forms.SendKeys]::SendWait("^a");',
            'Start-Sleep -Milliseconds 80;',
            '[System.Windows.Forms.SendKeys]::SendWait("^c");',
            'Start-Sleep -Milliseconds 80;'
        ].join(' ');
        execSync(`powershell -NoProfile -Command "${psScript}"`, { timeout: 3000 });
    } catch (e) {
        console.error('performCapture: SendKeys failed:', e.message);
    }

    // Step 2: Wait for clipboard to settle
    await new Promise(r => setTimeout(r, 150));

    // Step 3: Read and parse clipboard
    const text = clipboard.readText();
    if (!text || !text.trim()) {
        if (mainWindow) mainWindow.webContents.send('capture-result',
            { success: false, reason: 'empty' });
        return;
    }

    slots.hpi = extractHPI(text) || null;
    slots.ap  = extractAP(text)  || null;
    const exam = getExamSlot();

    if (mainWindow) mainWindow.webContents.send('capture-result', {
        success: true,
        hpiLoaded:    !!slots.hpi,
        apLoaded:     !!slots.ap,
        examLoaded:   !!exam,
        hpiPreview:   slots.hpi ? slots.hpi.substring(0, 80) : null,
        apPreview:    slots.ap  ? slots.ap.substring(0, 80)  : null,
        examPreview:  exam       ? exam.substring(0, 80)      : null,
        bulletsLoading: !!slots.ap
    });

    // Step 4: Fire bullet enrichment in background
    if (slots.ap) {
        const originalAP = slots.ap;
        extractActionItems(originalAP).then(bullets => {
            if (bullets && bullets.trim() && slots.ap === originalAP) {
                slots.ap = originalAP + '\n\n' + bullets;
            }
            if (mainWindow) mainWindow.webContents.send('bullets-ready', {
                apPreview: slots.ap ? slots.ap.substring(0, 80) : null
            });
        });
    }
}

function pasteSlot(slotName) {
    let content;
    if      (slotName === 'hpi')  content = slots.hpi;
    else if (slotName === 'exam') content = getExamSlot();
    else if (slotName === 'ap')   content = slots.ap;

    if (content && content.trim()) {
        clipboard.writeText(content);
        if (mainWindow) mainWindow.webContents.send('slot-pasted', slotName);

        // Auto-paste into the active window (Citrix) via PowerShell SendKeys
        setTimeout(() => {
            try {
                const psScript = [
                    'Add-Type -AssemblyName System.Windows.Forms;',
                    'Start-Sleep -Milliseconds 80;',
                    '[System.Windows.Forms.SendKeys]::SendWait("^v");'
                ].join(' ');
                execSync(`powershell -NoProfile -Command "${psScript}"`,
                    { timeout: 3000 });
            } catch (e) {
                console.error('pasteSlot: SendKeys Ctrl+V failed:', e.message);
            }
        }, 100);

    } else {
        if (mainWindow) mainWindow.webContents.send('slot-empty', slotName);
    }
}

// ── Screen capture ──────────────────────────────────────────────────────────
// Captures the screen, shows a fullscreen overlay for region selection,
// returns the cropped NativeImage as a PNG data URL.

let screenshotImage = null; // NativeImage of full screen capture

ipcMain.handle('start-screen-capture', async () => {
    try {
        // Use center of main window to find correct display, fall back to primary
        const mainBounds = mainWindow.getBounds();
        const mainCenter = {
            x: mainBounds.x + Math.floor(mainBounds.width / 2),
            y: mainBounds.y + Math.floor(mainBounds.height / 2)
        };
        const allDisplays = screen.getAllDisplays();
        const primaryDisplay = screen.getPrimaryDisplay();
        let display = allDisplays.find(d =>
            mainCenter.x >= d.bounds.x &&
            mainCenter.x < d.bounds.x + d.bounds.width &&
            mainCenter.y >= d.bounds.y &&
            mainCenter.y < d.bounds.y + d.bounds.height
        ) || primaryDisplay;
        console.log('Capturing display:', display.id, 'bounds:', display.bounds);

        // Hide main window so it's not in the screenshot
        mainWindow.hide();
        await new Promise(r => setTimeout(r, 300));

        // Capture the screen
        const sources = await desktopCapturer.getSources({
            types: ['screen'],
            thumbnailSize: {
                width: display.bounds.width * display.scaleFactor,
                height: display.bounds.height * display.scaleFactor
            }
        });

        const source = sources.find(s => String(s.display_id) === String(display.id)) || sources[0];

        if (!source) {
            if (mainWindow && !mainWindow.isDestroyed()) {
                mainWindow.show(); mainWindow.focus(); mainWindow.setAlwaysOnTop(true);
            }
            return { success: false, error: 'No screen source found' };
        }

        screenshotImage = source.thumbnail;

        // Create overlay for selection — no fullscreen to avoid Citrix security blanking
        overlayWindow = new BrowserWindow({
            x: display.bounds.x,
            y: display.bounds.y,
            width: display.bounds.width,
            height: display.bounds.height,
            frame: false,
            alwaysOnTop: true,
            fullscreen: false,
            resizable: false,
            movable: false,
            skipTaskbar: true,
            webPreferences: {
                nodeIntegration: false,
                contextIsolation: true,
                preload: path.join(__dirname, 'overlay-preload.js')
            }
        });

        overlayWindow.loadFile(path.join(__dirname, 'overlay.html'));

        overlayWindow.webContents.on('did-finish-load', () => {
            const dataUrl = screenshotImage.toDataURL();
            overlayWindow.webContents.send('set-screenshot', dataUrl);
        });

        // Wait for selection or cancel
        return new Promise((resolve) => {
            const cleanup = () => {
                if (overlayWindow && !overlayWindow.isDestroyed()) {
                    overlayWindow.close();
                }
                overlayWindow = null;
                mainWindow.show();
                mainWindow.focus();
                mainWindow.setAlwaysOnTop(true);
            };

            ipcMain.once('selection-done', (event, rect) => {
                // rect = { x, y, width, height } in screen pixels
                if (rect && rect.width > 5 && rect.height > 5) {
                    const scaleFactor = display.scaleFactor;
                    const cropped = screenshotImage.crop({
                        x: Math.round(rect.x * scaleFactor),
                        y: Math.round(rect.y * scaleFactor),
                        width: Math.round(rect.width * scaleFactor),
                        height: Math.round(rect.height * scaleFactor)
                    });
                    cleanup();
                    resolve({ success: true, imageDataUrl: cropped.toDataURL() });
                } else {
                    cleanup();
                    resolve({ success: false, cancelled: true });
                }
            });

            ipcMain.once('selection-cancel', () => {
                cleanup();
                resolve({ success: false, cancelled: true });
            });

            overlayWindow.on('closed', () => {
                overlayWindow = null;
                // If closed without selection
                mainWindow.show();
                mainWindow.setAlwaysOnTop(true);
                resolve({ success: false, cancelled: true });
            });
        });
    } catch (err) {
        console.error('Screen capture error:', err);
        try {
            if (mainWindow && !mainWindow.isDestroyed()) {
                mainWindow.show(); mainWindow.focus(); mainWindow.setAlwaysOnTop(true);
            }
            if (overlayWindow && !overlayWindow.isDestroyed()) {
                overlayWindow.close(); overlayWindow = null;
            }
        } catch (e) { /* ignore cleanup errors */ }
        return { success: false, error: err.message };
    }
});

// ── IPC handlers ────────────────────────────────────────────────────────────

ipcMain.handle('get-settings', () => {
    return {
        hpiHotkey:                store.get('hpiHotkey'),
        apHotkey:                 store.get('apHotkey'),
        heidiCopyEnabled:         store.get('heidiCopyEnabled'),
        captureHotkey:            store.get('captureHotkey'),
        pasteHotkey1:             store.get('pasteHotkey1'),
        pasteHotkey2:             store.get('pasteHotkey2'),
        pasteHotkey3:             store.get('pasteHotkey3'),
        examDotPhrase:            store.get('examDotPhrase'),
        claudeApiKey:             store.get('claudeApiKey'),
        customClaudeInstructions: store.get('customClaudeInstructions'),
        customAttestationTemplate:store.get('customAttestationTemplate')
    };
});

ipcMain.handle('get-app-info', () => ({
    version:   BUILD_INFO.version,
    commit:    BUILD_INFO.commit,
    builtAt:   BUILD_INFO.builtAt,
    runNumber: BUILD_INFO.runNumber,
    model:     CLAUDE_MODEL
}));

ipcMain.handle('save-settings', (e, settings) => {
    store.set('hpiHotkey',                settings.hpiHotkey);
    store.set('apHotkey',                 settings.apHotkey);
    store.set('heidiCopyEnabled',         settings.heidiCopyEnabled);
    store.set('captureHotkey',            settings.captureHotkey);
    store.set('pasteHotkey1',             settings.pasteHotkey1);
    store.set('pasteHotkey2',             settings.pasteHotkey2);
    store.set('pasteHotkey3',             settings.pasteHotkey3);
    store.set('examDotPhrase',            settings.examDotPhrase);
    store.set('claudeApiKey',             settings.claudeApiKey);
    store.set('customClaudeInstructions', settings.customClaudeInstructions);
    store.set('customAttestationTemplate',settings.customAttestationTemplate);
    writeAhkConfig(settings.examDotPhrase || '');
    sendSlotState();
    registerHotkeys();
    return true;
});

ipcMain.handle('call-claude-api', async (event, text) => {
    const customInstructions = store.get('customClaudeInstructions');
    return await callClaudeAPI(text, customInstructions);
});

ipcMain.handle('copy-to-clipboard', (event, text) => {
    clipboard.writeText(text);
    return true;
});

ipcMain.handle('get-attestation-template', () => {
    const custom = store.get('customAttestationTemplate');
    if (custom && custom.trim()) {
        return custom;
    }
    return DEFAULT_ATTESTATION_TEMPLATE;
});

ipcMain.handle('get-slot-state', () => ({
    hpiLoaded:   !!slots.hpi,
    apLoaded:    !!slots.ap,
    examLoaded:  !!getExamSlot(),
    hpiPreview:  slots.hpi      ? slots.hpi.substring(0, 80)      : null,
    apPreview:   slots.ap       ? slots.ap.substring(0, 80)       : null,
    examPreview: getExamSlot()  ? getExamSlot().substring(0, 80)  : null
}));

ipcMain.handle('set-window-collapsed', (event, collapsed) => {
    if (!mainWindow) return;
    const COLLAPSED_CONTENT_HEIGHT = 36;
    // Native frame (OS title bar + borders) height — on Windows this is ~32px,
    // so sizing the OUTER window to 36 hides the HTML title bar entirely.
    const outerH = mainWindow.getSize()[1];
    const contentH = mainWindow.getContentSize()[1];
    const chrome = Math.max(0, outerH - contentH);
    const collapsedOuterHeight = COLLAPSED_CONTENT_HEIGHT + chrome;
    const currentBounds = mainWindow.getBounds();

    if (collapsed) {
        store.set('expandedHeight', currentBounds.height);
        mainWindow.setMinimumSize(180, collapsedOuterHeight);
        mainWindow.setBounds({
            ...currentBounds,
            height: collapsedOuterHeight
        }, true);
        mainWindow.setResizable(false);
    } else {
        const expandedHeight = store.get('expandedHeight', 500);
        mainWindow.setMinimumSize(180, 120);
        mainWindow.setResizable(true);
        mainWindow.setBounds({
            ...currentBounds,
            height: expandedHeight
        }, true);
    }
    return true;
});

ipcMain.handle('open-settings', () => { openSettings(); return true; });
ipcMain.handle('trigger-capture', async () => { await performCapture(); return true; });
ipcMain.handle('paste-slot', (e, name) => { pasteSlot(name); return true; });
ipcMain.handle('clear-slots', () => { slots.hpi = null; slots.ap = null; return true; });
ipcMain.handle('save-exam-dot-phrase', (e, text) => {
    store.set('examDotPhrase', text); return true;
});

// ── Claude API ──────────────────────────────────────────────────────────────

const BUILT_IN_API_KEY = ''; // Removed — set your key in Settings → Claude API

const BASE_SYSTEM_PROMPT = `You are a medical note reformatter. Transform the input according to these rules:

NAME REMOVAL:
- Delete all instances of "Dr. Haring"

MEDICATIONS:
- Continued/unchanged medications → combine into single bullet: "- Continue: [med1], [med2], [med3]"
- New medications → "- Start: [medication]"
- Stopped medications → "- Stop: [medication]"
- Changed medications → "- Change: [medication to new dosage/frequency]"
- Only include Start/Stop/Change bullets when actual changes exist

RECOMMENDATIONS:
- Preserve "Consider" language verbatim (don't convert to directives)

PROCEDURES:
- Each procedure gets its own bullet point
- Note if procedure was "performed today" vs "scheduled"

ABBREVIATIONS (expand all):
- BID → twice daily
- TID → three times daily
- QID → four times daily
- QD → once daily
- PRN → as needed
- PO → by mouth
- IM → intramuscular
- IV → intravenous
- ESI → epidural steroid injection
- TFESI → transforaminal epidural steroid injection
- ILESI → interlaminar epidural steroid injection
- CESI → caudal epidural steroid injection
- RFA → radiofrequency ablation
- MBB → medial branch block
- SI → sacroiliac
- SIJ → sacroiliac joint
- CRPS → complex regional pain syndrome
- PT → physical therapy
- OT → occupational therapy
- MRI → magnetic resonance imaging
- CT → computed tomography
- EMG → electromyography
- NCS → nerve conduction study
- NSAID → nonsteroidal anti-inflammatory drug
- HA → headache
- LBP → low back pain
- ROM → range of motion
- WNL → within normal limits
- F/U → follow up
- RTC → return to clinic

OUTPUT FORMAT:
- Use dash-space bullets ( - )
- No blank lines between bullets
- Single line per bullet (no wrapping)
- No nested sub-bullets
- Output ONLY the formatted bullets, no explanations
- At the END, on a new line, output one of these codes based on content:
  [CODE:NO_CHANGES] - if no medication changes and no procedures
  [CODE:MED_CHANGES] - if medication changes only (Start/Stop/Change present)
  [CODE:MED_AND_SCHEDULED] - if medication changes AND a scheduled procedure
  [CODE:PROCEDURE_TODAY] - if a procedure was performed today`;

const ACTION_ITEM_PROMPT = `You are a medical note assistant. Given an Assessment and Plan section from a clinical note, extract only the concrete action items and output them as a concise bullet list.

INCLUDE these categories (when present):
- Medication changes: start, stop, or change (keep drug names and doses as written)
- Procedures ordered or scheduled
- Referrals
- Labs or imaging ordered
- Follow-up instructions (e.g. return to clinic timeframes)

DO NOT include:
- Diagnoses or problem descriptions
- Findings or exam results
- Rationale or explanations
- Anything that is not a discrete action

FORMAT:
- Use dash-space bullets (- )
- One action per bullet
- Keep abbreviations as-is (do not expand)
- No blank lines between bullets
- No preamble, headers, or explanation — output ONLY the bullet list
- If no action items are found, output nothing — return an empty string`;

async function extractActionItems(apText) {
    const apiKey = (store.get('claudeApiKey') || '').trim() || BUILT_IN_API_KEY;

    if (!apiKey || apiKey === '') {
        console.error('extractActionItems: No API key available');
        if (mainWindow) mainWindow.webContents.send('bullets-ready', {
            apPreview: null,
            error: 'No API key — go to Settings → Claude API to enter your key'
        });
        return null;
    }

    try {
        const response = await net.fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01'
            },
            body: JSON.stringify({
                model: CLAUDE_MODEL,
                max_tokens: 512,
                system: ACTION_ITEM_PROMPT,
                messages: [{ role: 'user', content: apText }]
            })
        });
        const data = await response.json();
        if (!response.ok) {
            console.error('extractActionItems API error:', data.error?.message || response.status);
            throw new Error(data.error?.message || `HTTP ${response.status}`);
        }
        return (data.content[0].text || '').trim();
    } catch (e) {
        console.error('Action item extraction failed:', e.message);
        return null;
    }
}

const DEFAULT_ATTESTATION_TEMPLATE = `For this patient encounter, I personally saw this patient and formulated the plan together with the APP at the time of this visit. I agree with the [DYNAMIC_PLAN_TEXT]. I reviewed the APP's documentation, medical decision making and treatment plan, and agree with the documentation above. By my electronic signature I authenticate all APP orders and attest that all pages have been reviewed and completed.

Physical exam: Gen: No acute distress
HEENT: EOMI, NC/AT
CV: Extremities warm and perfused.
Pulm: No increased work of breathing.
Neuro: Moves extremities spontaneously. Alert and oriented.
Psych: Answered all questions appropriately.

Assessment: As above

Plan:

`;

async function callClaudeAPI(text, customInstructions) {
    const apiKey = store.get('claudeApiKey') || BUILT_IN_API_KEY;
    if (!apiKey || !apiKey.trim()) {
        return { success: false, error: 'No API key set. Go to Settings → Claude API to enter your key.' };
    }

    let systemPrompt = BASE_SYSTEM_PROMPT;
    if (customInstructions && customInstructions.trim()) {
        systemPrompt += '\n\nADDITIONAL INSTRUCTIONS:\n' + customInstructions;
    }

    try {
        const response = await net.fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': apiKey,
                'anthropic-version': '2023-06-01'
            },
            body: JSON.stringify({
                model: CLAUDE_MODEL,
                max_tokens: 4096,
                system: systemPrompt,
                messages: [{ role: 'user', content: text }]
            })
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error?.message || 'API error');
        }

        return { success: true, text: data.content[0].text };
    } catch (error) {
        return { success: false, error: error.message };
    }
}

// ── App lifecycle ───────────────────────────────────────────────────────────

function migrateHotkeys() {
    const altKeys = ['Alt+C', 'Alt+1', 'Alt+2', 'Alt+3', 'Alt+X', 'Alt+Z', 'Alt+H', 'Alt+4', 'Alt+5', 'Alt+6'];
    const migrations = { captureHotkey: 'F8', pasteHotkey1: 'F9', pasteHotkey2: 'F10', pasteHotkey3: 'F11' };
    for (const [key, defaultVal] of Object.entries(migrations)) {
        const current = store.get(key);
        if (!current || altKeys.includes(current)) { store.set(key, defaultVal); }
    }
}
migrateHotkeys();

app.whenReady().then(() => {
    try {
        createMainWindow();
        registerHotkeys();
        if (process.platform === 'win32') {
            writeAhkConfig(store.get('examDotPhrase') || '');
            launchAHK();
            watchSlotsFile();
        }
    } catch (err) {
        const { dialog } = require('electron');
        dialog.showErrorBox(
            'MedicalNoteAttestor — Startup Error',
            'Failed to start:\n\n' + err.message + '\n\n' + (err.stack || '')
        );
        app.quit();
    }
    app.on('activate', () => {
        if (BrowserWindow.getAllWindows().length === 0) {
            createMainWindow();
        }
    });
}).catch(err => {
    try {
        require('electron').dialog.showErrorBox(
            'MedicalNoteAttestor — Fatal Error',
            'Fatal startup error:\n\n' + err.message + '\n\n' + (err.stack || '')
        );
    } catch(e) {}
    app.quit();
});

app.on('window-all-closed', () => { globalShortcut.unregisterAll(); killAHK(); app.quit(); });

app.on('will-quit', () => { globalShortcut.unregisterAll(); killAHK(); });
